use Euratex

/*==============================================================*/
/* FUNCTIES							                            */
/*==============================================================*/
-- Geeft het risico terug op basis van ERNST_VAN_HET_ONGEVAL, KANS_OP_BLOOTSTELLING en KANS_OP_WAARSCHIJNLIJKHEID.
GO
CREATE FUNCTION dbo.FN_GET_RISICO (
	@ERNST_VAN_HET_ONGEVAL NUMERIC(9, 2), 
	@KANS_OP_BLOOTSTELLING NUMERIC(9, 2), 
	@KANS_OP_WAARSCHIJNLIJKHEID NUMERIC(9, 2)
) RETURNS NUMERIC(9, 2) AS BEGIN
	RETURN (@ERNST_VAN_HET_ONGEVAL * @KANS_OP_BLOOTSTELLING * @KANS_OP_WAARSCHIJNLIJKHEID)
END
GO

-- Geeft de prioriteit van een risico terug.
GO
CREATE FUNCTION dbo.FN_GET_PRIORITEIT (
	@RISICO NUMERIC(9, 2)
) RETURNS VARCHAR(255) AS BEGIN
	DECLARE @PRIORITEIT VARCHAR(255)

	IF(@RISICO <= 20) BEGIN
		SET @PRIORITEIT = 'P 5'
	END ELSE IF(@RISICO >= 21 AND @RISICO <= 75) BEGIN
		SET @PRIORITEIT = 'P 4'
	END ELSE IF(@RISICO >= 76 AND @RISICO <= 200) BEGIN
		SET @PRIORITEIT = 'P 3'
	END ELSE IF(@RISICO >= 201 AND @RISICO <= 400) BEGIN
		SET @PRIORITEIT = 'P 2'
	END ELSE BEGIN
		SET @PRIORITEIT = 'P 1'
	END

	RETURN @PRIORITEIT
END
GO

/*==============================================================*/
/* KOLOMMEN							                            */
/*==============================================================*/
-- Voor

alter table RISICOREGEL
drop column VOOR_RISICO

alter table RISICOREGEL
add VOOR_RISICO AS dbo.FN_GET_RISICO(VOOR_ERNST_VAN_HET_ONGEVAL, VOOR_KANS_OP_BLOOTSTELLING, VOOR_KANS_OP_WAARSCHIJNLIJKHEID)

alter table RISICOREGEL
drop column VOOR_PRIORITEIT

alter table RISICOREGEL
add VOOR_PRIORITEIT AS dbo.FN_GET_PRIORITEIT(dbo.FN_GET_RISICO(VOOR_ERNST_VAN_HET_ONGEVAL, VOOR_KANS_OP_BLOOTSTELLING, VOOR_KANS_OP_WAARSCHIJNLIJKHEID))

-- Na

alter table RISICOREGEL
drop column NA_RISICO

alter table RISICOREGEL
add NA_RISICO AS dbo.FN_GET_RISICO(VOOR_ERNST_VAN_HET_ONGEVAL, VOOR_KANS_OP_BLOOTSTELLING, VOOR_KANS_OP_WAARSCHIJNLIJKHEID)

alter table RISICOREGEL
drop column NA_PRIORITEIT

alter table RISICOREGEL
add NA_PRIORITEIT AS dbo.FN_GET_PRIORITEIT(dbo.FN_GET_RISICO(VOOR_ERNST_VAN_HET_ONGEVAL, VOOR_KANS_OP_BLOOTSTELLING, VOOR_KANS_OP_WAARSCHIJNLIJKHEID))

use master