GO
CREATE PROCEDURE SELECT_RISICOREGEL
	@PROJECTNUMMER INT,
	@RAPPORTNUMMER INT,
	@REGELNUMMER INT
AS BEGIN
	SELECT RR.*, FEK_VOOR.ERNST_VAN_HET_ONGEVAL AS 'VOOR_ERNST_VAN_HET_ONGEVAL', FEK_VOOR.KANS_OP_BLOOTSTELLING AS 'VOOR_KANS_OP_BLOOTSTELLING', FEK_VOOR.KANS_OP_WAARSCHIJNLIJKHEID AS 'VOOR_KANS_OP_WAARSCHIJNLIJKHEID', RM.*
	FROM RISICOREGEL RR INNER JOIN FINE_EN_KINNEY FEK_VOOR
	ON RR.PROJECTNUMMER = FEK_VOOR.PROJECTNUMMER
	AND RR.RAPPORTNUMMER = FEK_VOOR.RAPPORTNUMMER
	AND RR.REGELNUMMER = FEK_VOOR.REGELNUMMER
	AND FEK_VOOR.FINE_EN_KINNEY_TYPE = 'Voor'
	INNER JOIN FINE_EN_KINNEY FEK_NA
	ON RR.PROJECTNUMMER = FEK_NA.PROJECTNUMMER
	AND RR.RAPPORTNUMMER = FEK_NA.RAPPORTNUMMER
	AND RR.REGELNUMMER = FEK_NA.REGELNUMMER
	AND FEK_NA.FINE_EN_KINNEY_TYPE = 'Na'
	INNER JOIN RISICOMAATREGEL RM
	ON RR.PROJECTNUMMER = RM.PROJECTNUMMER
	AND RR.RAPPORTNUMMER = RM.RAPPORTNUMMER
	AND RR.REGELNUMMER = RM.REGELNUMMER
	WHERE RR.PROJECTNUMMER = @PROJECTNUMMER
	AND RR.RAPPORTNUMMER = @RAPPORTNUMMER
	AND RR.REGELNUMMER = @REGELNUMMER
END
GO



EXEC dbo.SELECT_RISICOREGEL 1, 1, 1



SELECT R. FROM RAPPORT WHERE PROJECTNUMMER = 1