CREATE PROCEDURE SP_INSERT_RAPPORT
		@PROJECTNUMMER      INT,
		@RAPPORT_TYPE		VARCHAR(255)
AS
	BEGIN
		SET NOCOUNT, XACT_ABORT ON
		DECLARE @TranCounter INT;
		SET @TranCounter = @@TRANCOUNT;

		IF @TranCounter > 0
			SAVE TRANSACTION ProcedureSave;
		ELSE
			BEGIN TRANSACTION;

		BEGIN TRY
		--Ophoging rapportnummer
				DECLARE @RAPPORTNUMMER INT = (
			SELECT ISNULL(MAX(RAPPORTNUMMER), 0) + 1
			FROM RAPPORT
			WHERE PROJECTNUMMER = @PROJECTNUMMER)


		--1. Project insert
		INSERT INTO RAPPORT(RAPPORTNUMMER,PROJECTNUMMER,RAPPORT_TYPE)
		VALUES (@RAPPORTNUMMER, @PROJECTNUMMER, @RAPPORT_TYPE)

		IF @TranCounter = 0 AND XACT_STATE() = 1
			COMMIT TRANSACTION;
		END TRY
		BEGIN CATCH
		IF @TranCounter = 0
			BEGIN
				IF XACT_STATE() = 1
					ROLLBACK TRANSACTION;
			END;
		ELSE
			BEGIN
				IF XACT_STATE() <> -1
					ROLLBACK TRANSACTION ProcedureSave;
			END;
		THROW
		END CATCH
	END
GO
