CREATE TRIGGER TRG_VISUELE_BEOORDELING
	ON VISUELE_BEOORDELING
AFTER INSERT, UPDATE
AS BEGIN
		DECLARE @ROWCOUNT INT = @@ROWCOUNT
		IF @ROWCOUNT = 0 RETURN
	BEGIN TRY
		IF((SELECT LEN(PROCES)
			FROM inserted) < 2)
			IF((SELECT LEN(MACHINE_ONDERDEEL_) FROM inserted) < 2)
				IF((SELECT LEN(AFDELING) FROM inserted) < 2)
					RAISERROR ('Een van de 3 visuele beoordeling waardes moet worden ingevuld', 16, 1)
	END TRY
	BEGIN CATCH
		THROW
	END CATCH
END
